CREATE TABLE nav_codes (
    status_code INT PRIMARY KEY,
    status_code_description VARCHAR(255)
);

INSERT INTO nav_codes (status_code, status_code_description) VALUES
    (0, 'Under way using engine'),
    (1, 'At anchor'),
    (2, 'Not under command'),
    (3, 'Has restricted maneuverability'),
    (4, 'Ship draught is limiting its movement'),
    (5, 'Moored (tied to another object to limit free movement)'),
    (6, 'Aground'),
    (7, 'Engaged in Fishing'),
    (8, 'Under way sailing'),
    (9, 'Reserved for future amendment of navigational status for ships carrying DG, HS, or MP, or IMO hazard or pollutant category C, high speed craft (HSC)'),
    (10, 'Reserved for future amendment of navigational status for ships carrying dangerous goods (DG), harmful substances (HS) or marine pollutants (MP), or IMO hazard or pollutant category A, wing in ground (WIG)'),
    (11, 'Power-driven vessel towing astern'),
    (12, 'Power-driven vessel pushing ahead/towing alongside'),
    (13, 'Reserved for future use'),
    (14, 'AIS-SART (Search and Rescue Transmitter), AIS-MOB (Man Overboard) or AIS-EPIRB (Emergency Position Indicating Radio Beacon)'),
    (15, 'Not defined (default)');

CREATE TABLE mid_country_codes (
    mid_code INT PRIMARY KEY,
    country_name VARCHAR(255),
    country_code CHAR(2)
);

INSERT INTO mid_country_codes (mid_code, country_name, country_code) VALUES
    (201, 'Albania', 'AL'),
    (202, 'Andorra', 'AD'),
    (203, 'Austria', 'AT'),
    (204, 'Portugal', 'PT'),
    (205, 'Belgium', 'BE'),
    (206, 'Belarus', 'BY'),
    (207, 'Bulgaria', 'BG'),
    (208, 'Vatican', 'VA'),
    (209, 'Cyprus', 'CY'),
    (210, 'Cyprus', 'CY'),
    (211, 'Germany', 'DE'),
    (212, 'Cyprus', 'CY'),
    (213, 'Georgia', 'GE'),
    (214, 'Moldova', 'MD'),
    (215, 'Malta', 'MT'),
    (216, 'Armenia', 'AM'),
    (218, 'Germany', 'DE'),
    (219, 'Denmark', 'DK'),
    (220, 'Denmark', 'DK'),
    (224, 'Spain', 'ES'),
    (225, 'Spain', 'ES'),
    (226, 'France', 'FR'),
    (227, 'France', 'FR'),
    (228, 'France', 'FR'),
    (229, 'Malta', 'MT'),
    (230, 'Finland', 'FI'),
    (231, 'Faroe Is', 'FO'),
    (232, 'United Kingdom', 'GB'),
    (233, 'United Kingdom', 'GB'),
    (234, 'United Kingdom', 'GB'),
    (235, 'United Kingdom', 'GB'),
    (236, 'Gibraltar', 'GI'),
    (237, 'Greece', 'GR'),
    (238, 'Croatia', 'HR'),
    (239, 'Greece', 'GR'),
    (240, 'Greece', 'GR'),
    (241, 'Greece', 'GR'),
    (242, 'Morocco', 'MA'),
    (243, 'Hungary', 'HU'),
    (244, 'Netherlands', 'NL'),
    (245, 'Netherlands', 'NL'),
    (246, 'Netherlands', 'NL'),
    (247, 'Italy', 'IT'),
    (248, 'Malta', 'MT'),
    (249, 'Malta', 'MT'),
    (250, 'Ireland', 'IE'),
    (251, 'Iceland', 'IS'),
    (252, 'Liechtenstein', 'LI'),
    (253, 'Luxembourg', 'LU'),
    (254, 'Monaco', 'MC'),
    (255, 'Portugal', 'PT'),
    (256, 'Malta', 'MT'),
    (257, 'Norway', 'NO'),
    (258, 'Norway', 'NO'),
    (259, 'Norway', 'NO'),
    (261, 'Poland', 'PL'),
    (262, 'Montenegro', 'ME'),
    (263, 'Portugal', 'PT'),
    (264, 'Romania', 'RO'),
    (265, 'Sweden', 'SE'),
    (266, 'Sweden', 'SE'),
    (267, 'Slovakia', 'SK'),
    (268, 'San Marino', 'SM'),
    (269, 'Switzerland', 'CH'),
    (270, 'Czech Republic', 'CZ'),
    (271, 'Turkey', 'TR'),
    (272, 'Ukraine', 'UA'),
    (273, 'Russia', 'RU'),
    (274, 'FYR Macedonia', 'MK'),
    (275, 'Latvia', 'LV'),
    (276, 'Estonia', 'EE'),
    (277, 'Lithuania', 'LT'),
    (278, 'Slovenia', 'SI'),
    (279, 'Serbia', 'RS'),
    (301, 'Anguilla', 'AI'),
    (303, 'USA', 'US'),
    (304, 'Antigua Barbuda', 'AG'),
    (305, 'Antigua Barbuda', 'AG'),
    (306, 'Curacao', 'CW'),
    (307, 'Aruba', 'AW'),
    (308, 'Bahamas', 'BS'),
    (309, 'Bahamas', 'BS'),
    (310, 'Bermuda', 'BM'),
    (311, 'Bahamas', 'BS'),
    (312, 'Belize', 'BZ'),
    (314, 'Barbados', 'BB'),
    (316, 'Canada', 'CA'),
    (319, 'Cayman Is', 'KY'),
    (321, 'Costa Rica', 'CR'),
    (323, 'Cuba', 'CU'),
    (325, 'Dominica', 'DM'),
    (327, 'Dominican Rep', 'DO'),
    (329, 'Guadeloupe', 'GP'),
    (330, 'Grenada', 'GD'),
    (331, 'Greenland', 'GL'),
    (332, 'Guatemala', 'GT'),
    (334, 'Honduras', 'HN'),
    (336, 'Haiti', 'HT'),
    (338, 'USA', 'US'),
    (339, 'Jamaica', 'JM'),
    (341, 'St Kitts Nevis', 'KN'),
    (343, 'St Lucia', 'LC'),
    (345, 'Mexico', 'MX'),
    (347, 'Martinique', 'MQ'),
    (348, 'Montserrat', 'MS'),
    (350, 'Nicaragua', 'NI'),
    (351, 'Panama', 'PA'),
    (352, 'Panama', 'PA'),
    (353, 'Panama', 'PA'),
    (354, 'Panama', 'PA'),
    (355, 'Panama', 'PA'),
    (356, 'Panama', 'PA'),
    (357, 'Panama', 'PA'),
    (358, 'Puerto Rico', 'PR'),
    (359, 'El Salvador', 'SV'),
    (361, 'St Pierre Miquelon', 'PM'),
    (362, 'Trinidad Tobago', 'TT'),
    (364, 'Turks Caicos Is', 'TC'),
    (366, 'USA', 'US'),
    (367, 'USA', 'US'),
    (368, 'USA', 'US'),
    (369, 'USA', 'US'),
    (370, 'Panama', 'PA'),
    (371, 'Panama', 'PA'),
    (372, 'Panama', 'PA'),
    (373, 'Panama', 'PA'),
    (374, 'Panama', 'PA'),
    (375, 'St Vincent Grenadines', 'VC'),
    (376, 'St Vincent Grenadines', 'VC'),
    (377, 'St Vincent Grenadines', 'VC'),
    (378, 'British Virgin Is', 'VG'),
    (379, 'US Virgin Is', 'VI'),
    (401, 'Afghanistan', 'AF'),
    (403, 'Saudi Arabia', 'SA'),
    (405, 'Bangladesh', 'BD'),
    (408, 'Bahrain', 'BH'),
    (410, 'Bhutan', 'BT'),
    (412, 'China', 'CN'),
    (413, 'China', 'CN'),
    (414, 'China', 'CN'),
    (416, 'Taiwan', 'TW'),
    (417, 'Sri Lanka', 'LK'),
    (419, 'India', 'IN'),
    (422, 'Iran', 'IR'),
    (423, 'Azerbaijan', 'AZ'),
    (425, 'Iraq', 'IQ'),
    (428, 'Israel', 'IL'),
    (431, 'Japan', 'JP'),
    (432, 'Japan', 'JP'),
    (434, 'Turkmenistan', 'TM'),
    (436, 'Kazakhstan', 'KZ'),
    (437, 'Uzbekistan', 'UZ'),
    (438, 'Jordan', 'JO'),
    (440, 'Korea', 'KR'),
    (441, 'Korea', 'KR'),
    (443, 'Palestine', 'PS'),
    (445, 'DPR Korea', 'KP'),
    (447, 'Kuwait', 'KW'),
    (450, 'Lebanon', 'LB'),
    (451, 'Kyrgyz Republic', 'KG'),
    (453, 'Macao', 'MO'),
    (455, 'Maldives', 'MV'),
    (457, 'Mongolia', 'MN'),
    (459, 'Nepal', 'NP'),
    (461, 'Oman', 'OM'),
    (463, 'Pakistan', 'PK'),
    (466, 'Qatar', 'QA'),
    (468, 'Syria', 'SY'),
    (470, 'UAE', 'AE'),
    (471, 'UAE', 'AE'),
    (472, 'Tajikistan', 'TJ'),
    (473, 'Yemen', 'YE'),
    (475, 'Yemen', 'YE'),
    (477, 'Hong Kong', 'HK'),
    (478, 'Bosnia and Herzegovina', 'BA'),
    (501, 'Antarctica', 'AQ'),
    (503, 'Australia', 'AU'),
    (506, 'Myanmar', 'MM'),
    (508, 'Brunei', 'BN'),
    (510, 'Micronesia', 'FM'),
    (511, 'Palau', 'PW'),
    (512, 'New Zealand', 'NZ'),
    (514, 'Cambodia', 'KH'),
    (515, 'Cambodia', 'KH'),
    (516, 'Christmas Is', 'CX'),
    (518, 'Cook Is', 'CK'),
    (520, 'Fiji', 'FJ'),
    (523, 'Cocos Is', 'CC'),
    (525, 'Indonesia', 'ID'),
    (529, 'Kiribati', 'KI'),
    (531, 'Laos', 'LA'),
    (533, 'Malaysia', 'MY'),
    (536, 'N Mariana Is', 'MP'),
    (538, 'Marshall Is', 'MH'),
    (540, 'New Caledonia', 'NC'),
    (542, 'Niue', 'NU'),
    (544, 'Nauru', 'NR'),
    (546, 'French Polynesia', 'PF'),
    (548, 'Philippines', 'PH'),
    (553, 'Papua New Guinea', 'PG'),
    (555, 'Pitcairn Is', 'PN'),
    (557, 'Solomon Is', 'SB'),
    (559, 'American Samoa', 'AS'),
    (561, 'Samoa', 'WS'),
    (563, 'Singapore', 'SG'),
    (564, 'Singapore', 'SG'),
    (565, 'Singapore', 'SG'),
    (566, 'Singapore', 'SG'),
    (567, 'Thailand', 'TH'),
    (570, 'Tonga', 'TO'),
    (572, 'Tuvalu', 'TV'),
    (574, 'Vietnam', 'VN'),
    (576, 'Vanuatu', 'VU'),
    (577, 'Vanuatu', 'VU'),
    (578, 'Wallis Futuna Is', 'WF'),
    (601, 'South Africa', 'ZA'),
    (603, 'Angola', 'AO'),
    (605, 'Algeria', 'DZ'),
    (607, 'St Paul Amsterdam Is', 'TF'),
    (608, 'Ascension Is', 'IO'),
    (609, 'Burundi', 'BI'),
    (610, 'Benin', 'BJ'),
    (611, 'Botswana', 'BW'),
    (612, 'Cen Afr Rep', 'CF'),
    (613, 'Cameroon', 'CM'),
    (615, 'Congo', 'CG'),
    (616, 'Comoros', 'KM'),
    (617, 'Cape Verde', 'CV'),
    (618, 'Antarctica', 'AQ'),
    (619, 'Ivory Coast', 'CI'),
    (620, 'Comoros', 'KM'),
    (621, 'Djibouti', 'DJ'),
    (622, 'Egypt', 'EG'),
    (624, 'Ethiopia', 'ET'),
    (625, 'Eritrea', 'ER'),
    (626, 'Gabon', 'GA'),
    (627, 'Ghana', 'GH'),
    (629, 'Gambia', 'GM'),
    (630, 'Guinea-Bissau', 'GW'),
    (631, 'Equ. Guinea', 'GQ'),
    (632, 'Guinea', 'GN'),
    (633, 'Burkina Faso', 'BF'),
    (634, 'Kenya', 'KE'),
    (635, 'Antarctica', 'AQ'),
    (636, 'Liberia', 'LR'),
    (637, 'Liberia', 'LR'),
    (642, 'Libya', 'LY'),
    (644, 'Lesotho', 'LS'),
    (645, 'Mauritius', 'MU'),
    (647, 'Madagascar', 'MG'),
    (649, 'Mali', 'ML'),
    (650, 'Mozambique', 'MZ'),
    (654, 'Mauritania', 'MR'),
    (655, 'Malawi', 'MW'),
    (656, 'Niger', 'NE'),
    (657, 'Nigeria', 'NG'),
    (659, 'Namibia', 'NA'),
    (660, 'Reunion', 'RE'),
    (661, 'Rwanda', 'RW'),
    (662, 'Sudan', 'SD'),
    (663, 'Senegal', 'SN'),
    (664, 'Seychelles', 'SC'),
    (665, 'St Helena', 'SH'),
    (666, 'Somalia', 'SO'),
    (667, 'Sierra Leone', 'SL'),
    (668, 'Sao Tome Principe', 'ST'),
    (669, 'Swaziland', 'SZ'),
    (670, 'Chad', 'TD'),
    (671, 'Togo', 'TG'),
    (672, 'Tunisia', 'TN'),
    (674, 'Tanzania', 'TZ'),
    (675, 'Uganda', 'UG'),
    (676, 'DR Congo', 'CD'),
    (677, 'Tanzania', 'TZ'),
    (678, 'Zambia', 'ZM'),
    (679, 'Zimbabwe', 'ZW'),
    (701, 'Argentina', 'AR'),
    (710, 'Brazil', 'BR'),
    (720, 'Bolivia', 'BO'),
    (725, 'Chile', 'CL'),
    (730, 'Colombia', 'CO'),
    (735, 'Ecuador', 'EC'),
    (740, 'UK', 'UK'),
    (745, 'Guiana', 'GF'),
    (750, 'Guyana', 'GY'),
    (755, 'Paraguay', 'PY'),
    (760, 'Peru', 'PE'),
    (765, 'Suriname', 'SR'),
    (770, 'Uruguay', 'UY'),
    (775, 'Venezuela', 'VE');


CREATE TABLE fix_types(
    fix_type_code INT PRIMARY KEY,
    fix_type_description VARCHAR(255)
);
INSERT INTO fix_types (fix_type_code, fix_type_description) VALUES
    (0, 'Not available'),
    (1, 'GPS'),
    (2, 'GLONASS'),
    (3, 'Combined GNSS'),
    (4, 'Loran'),
    (5, 'Chayka'),
    (6, 'INS'),
    (7, 'Manually inputted'),
    (8, 'Galileo'),
    (9, 'BDS'),
    (10, 'Not used'),
    (11, 'Not used'),
    (12, 'Integrated PNT system'),
    (13, 'Inertial navigation system'),
    (14, 'Terrestrial radio navigation system'),
    (15, 'Internal GNSS');


CREATE TABLE ship_types (
    type_code INT PRIMARY KEY,
    type_description VARCHAR(255) NOT NULL
);

INSERT INTO ship_types (type_code, type_description) VALUES
    (1, 'Science/Research vessel'),
    (2, 'Training vessel'),
    (3, 'Ship owned or operated by a government'),
    (4, 'Ice breaker'),
    (5, 'Buoy (Aids to Navigation) tender'),
    (6, 'Cable layer'),
    (7, 'Pipe layer'),
    (8, 'Reserved for future use'),
    (9, 'Special purpose ship, no additional information'),
    (10, 'Reserved for future use'),
    (11, 'FPSO (Floating, Production, Storage, Offloading) vessel'),
    (12, 'Fish factory ship'),
    (13, 'Fish farm support vessel'),
    (14, 'Offshore support vessel, etc.'),
    (15, 'Reserved for future use'),
    (16, 'Reserved for future use'),
    (17, 'Construction vessel'),
    (18, 'Crew boat'),
    (19, 'Support vessel, no additional information'),
    (20, 'WIG, all ships of this type'),
    (21, 'WIG, carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category X'),
    (22, 'WIG, carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category Y'),
    (23, 'WIG, carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category Z'),
    (24, 'WIG, carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category OS'),
    (25, 'Reserved for future use'),
    (26, 'Reserved for future use'),
    (27, 'Reserved for future use'),
    (28, 'Reserved for future use'),
    (29, 'WIG vessel, no additional information'),
    (30, 'Fishing vessel'),
    (31, 'Towing'),
    (32, 'Towing and length of the tow exceeds 200 m or breadth exceeds 25 m'),
    (33, 'Dredger'),
    (34, 'Diving vessel'),
    (35, 'Warship or naval auxiliary'),
    (36, 'Sailing vessel'),
    (37, 'Pleasure motor craft'),
    (38, 'Trawler'),
    (39, 'Patrol vessel'),
    (40, 'HSC, all ships of this type'),
    (41, 'HSC, carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category X'),
    (42, 'HSC, carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category Y'),
    (43, 'HSC, carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category Z'),
    (44, 'HSC, carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category OS'),
    (45, 'HSC, carrying passengers'),
    (46, 'HSC Ro-Ro ship (vehicle / rail)'),
    (47, 'Reserved for future use'),
    (48, 'Reserved for future use'),
    (49, 'HSC, no additional information'),
    (50, 'Pilot vessel'),
    (51, 'Search and rescue vessels'),
    (52, 'Tugs'),
    (53, 'Port or fish tenders'),
    (54, 'Anti-pollution or firefighting responder'),
    (55, 'Law enforcement vessels'),
    (56, 'Spare 1 for assignments to local vessels'),
    (57, 'Spare 2 for assignments to local vessels'),
    (58, 'Medical transports (as defined in the 1949 Geneva Conventions and Additional Protocols)'),
    (59, 'Ships of States not parties to an armed conflict'),
    (60, 'Passenger ships, all ships of this type'),
    (61, 'Passenger ships, carrying DG and/or MHB, HS, or MP cargo, IMO hazard or pollutant category X'),
    (62, 'Passenger ships, carrying DG and/or MHB, HS, or MP cargo, IMO hazard or pollutant category Y'),
    (63, 'Passenger ships, carrying DG and/or MHB, HS, or MP cargo, IMO hazard or pollutant category Z'),
    (64, 'Passenger ships, carrying DG and/or MHB, HS, or MP cargo, IMO hazard or pollutant category OS'),
    (65, 'Passenger (cruise) ship'),
    (66, 'Passenger (ferry) ship'),
    (67, 'Passenger (excursion) ship (i.e. harbour cruise boat, whale watcher, etc.)'),
    (68, 'Reserved for future use'),
    (69, 'Passenger ships, no additional information'),
    (70, 'Cargo ships, all ships of this type'),
    (71, 'Cargo ships, carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category X'),
    (72, 'Cargo ships, carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category Y'),
    (73, 'Cargo ships, carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category Z'),
    (74, 'Cargo ships, carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category OS'),
    (75, 'Cargo ship, bulk carrier'),
    (76, 'Cargo ship, container ship'),
    (77, 'Cargo ship, roll-on-roll-off carrier'),
    (78, 'Cargo ship, landing craft'),
    (79, 'Cargo ships, no additional information'),
    (80, 'Tanker(s), all ships of this type'),
    (81, 'Tanker(s), carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category X'),
    (82, 'Tanker(s), carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category Y'),
    (83, 'Tanker(s), carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category Z'),
    (84, 'Tanker(s), carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category OS'),
    (85, 'Tanker(s), non-hazardous or non-pollutant carrier'),
    (86, 'Integrated/articulated tug and tank barge (ABCD values should reflect tug and barge dimensions)'),
    (87, 'Reserved for future use'),
    (88, 'Reserved for future use'),
    (89, 'Tanker(s), no additional information'),
    (90, 'Other types of ship'),
    (91, 'Other types of ships, carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category X'),
    (92, 'Other types of ships, carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category Y'),
    (93, 'Other types of ships, carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category Z'),
    (94, 'Other types of ships, carrying DG and/or MHB, HS, or MP, IMO hazard or pollutant category OS'),
    (95, 'Reserved for future use'),
    (96, 'Reserved for future use'),
    (97, 'Reserved for future use'),
    (98, 'Reserved for future use'),
    (99, 'Other types of ship, no additional information');